name: Comment Build
on:
  issue_comment:
    types: [ created ]

jobs:
  commentBuild:
    name: Release Build
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/release')
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # JDK 설정
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
         distribution: "zulu"
         java-version: 11

      # Android SDK 설정
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # gradlew 접근을 위한 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # SERVER_URL 불러오기
      - name: Load CARSSOK_SERVER_URL
        env:
          CARSSOK_SERVER_URL: ${{ secrets.CARSSOK_SERVER_URL }}
        run: echo carssok_url=\"$CARSSOK_SERVER_URL\" > ./local.properties

      # google-service.json 파일 생성
      - name: Create google-service.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON > ./app/google-services.json

      # keystore.properties 파일 생성 (release 전용)
      - name: Create keystore.properties
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_FILE: ${{ secrets.KEYSTORE_STORE_FILE }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        run: |
          echo storeFile=$KEYSTORE_STORE_FILE > ./keystore/keystore.properties
          echo storePassword=$KEYSTORE_STORE_PASSWORD >> ./keystore/keystore.properties
          echo keyPassword=$KEYSTORE_KEY_PASSWORD >> ./keystore/keystore.properties
          echo keyAlias=$KEYSTORE_KEY_ALIAS >> ./keystore/keystore.properties

      # keystore.jks 파일 생성 (release 전용)
      - name: Create keystore.jks file
        env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
        run: |
          echo $KEYSTORE_JKS_BASE64 > ./keystore/keystore-base64.txt
          base64 -d -i ./keystore/keystore-base64.txt > ./keystore/keystore.jks

      # 빌드
      - name: Build release apk
        run: ./gradlew assembleRelease

      # 배포
      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 28.8
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotesFile: documents/release-note/release_note.txt