name: Build & Publish to Firebase App Distribution
on:
  pull_request:
    types: [ opened, ready_for_review, synchronize ]
    branches: [ release/**, master ]
    paths-ignore:
      - '**.md'
      - '**.html'

jobs:
  build:
    name: "Build & Publish"
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # JDK 설정
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      # Android SDK 설정
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew 접근을 위한 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # SERVER_URL 불러오기
      - name: Load CARSSOK_SERVER_URL
        env:
          CARSSOK_SERVER_URL: ${{ secrets.CARSSOK_SERVER_URL }}
        run: echo carssok_url=\"$CARSSOK_SERVER_URL\" > ./local.properties

      # google-service.json 파일 생성
      - name: Create google-service.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON > ./app/google-services.json

      # keystore.properties 파일 생성 (release 전용)
      - name: Create keystore.properties
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: echo $KEYSTORE_RELEASE_PROPERTIES > ./keystore/keystore.properties

      # keystore.jks 파일 생성 (release 전용)
      - name: Create keystore.jks file
        run: |
          echo "$KEYSTORE" > ./keystore/keystore-base64.txt
          base64 -d -i ./keystore/keystore-base64.txt > ./keystore/keystore.jks
        env:
          KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}

      # 빌드
      - name: Build debug apk
        run: ./gradlew assembleDebug

      # 배포
      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 28.8
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotesFile: documents/release-note/release_note.txt

#build, publish로 job을 분리할 경우, job 간에 apk 공유를 위한 추가 작업이 필요하기 때문에, 단일 job으로 구성
#추후 job 분리가 필요할 경우 별도 작업